name: Replace version
description: |
  Replace version in packages/cli/package/src/versions.json

inputs:
  versions:
    description: "Versions JSON string"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
