/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.9.4
 *
 */
import { FluencePeer } from "@fluencelabs/fluence";
import type { CallParams$$ } from "@fluencelabs/fluence/dist/internal/compilerSupport/v4.js";
import {
  callFunction$$,
  registerService$$,
} from "@fluencelabs/fluence/dist/internal/compilerSupport/v4.js";

// Services

export interface ConsoleDef {
  print: (s: string, callParams: CallParams$$<"s">) => void | Promise<void>;
}
export function registerConsole(service: ConsoleDef): void;
export function registerConsole(serviceId: string, service: ConsoleDef): void;
export function registerConsole(peer: FluencePeer, service: ConsoleDef): void;
export function registerConsole(
  peer: FluencePeer,
  serviceId: string,
  service: ConsoleDef
): void;

export function registerConsole(...args: any) {
  registerService$$(args, {
    defaultServiceId: "run-console",
    functions: {
      tag: "labeledProduct",
      fields: {
        print: {
          tag: "arrow",
          domain: {
            tag: "labeledProduct",
            fields: {
              s: {
                tag: "scalar",
                name: "string",
              },
            },
          },
          codomain: {
            tag: "nil",
          },
        },
      },
    },
  });
}

// Functions
/* prettier-ignore-end */
