/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.10.2
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';



// Services

// Functions


export function blueprint_key(
    service_name: string,
    config?: {ttl?: number}
): Promise<string>;

export function blueprint_key(
    peer: IFluenceClient$$,
    service_name: string,
    config?: {ttl?: number}
): Promise<string>;

export function blueprint_key(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                        (call %init_peer_id% ("getDataSrv" "service_name") [] service_name)
                       )
                       (call %init_peer_id% ("op" "concat_strings") ["blueprint:" service_name] concat_strings)
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [concat_strings])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "blueprint_key",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "service_name" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "string"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}



export function is_deployed(
    service_name: string,
    blueprint_id: string,
    config?: {ttl?: number}
): Promise<boolean>;

export function is_deployed(
    peer: IFluenceClient$$,
    service_name: string,
    blueprint_id: string,
    config?: {ttl?: number}
): Promise<boolean>;

export function is_deployed(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                         (call %init_peer_id% ("getDataSrv" "service_name") [] service_name)
                        )
                        (call %init_peer_id% ("getDataSrv" "blueprint_id") [] blueprint_id)
                       )
                       (new $result
                        (seq
                         (seq
                          (seq
                           (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id)
                           (call %init_peer_id% (spell_id "exists") [service_name] deployed)
                          )
                          (xor
                           (match deployed.$.flag! true
                            (xor
                             (seq
                              (seq
                               (call %init_peer_id% ("op" "concat_strings") ["blueprint:" service_name] concat_strings)
                               (call %init_peer_id% (spell_id "get_string") [concat_strings] stored_blueprint)
                              )
                              (xor
                               (match stored_blueprint.$.str! blueprint_id
                                (ap true $result)
                               )
                               (ap false $result)
                              )
                             )
                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                            )
                           )
                           (ap false $result)
                          )
                         )
                         (new $result_test
                          (seq
                           (seq
                            (seq
                             (call %init_peer_id% ("math" "add") [0 1] result_incr)
                             (fold $result result_fold_var
                              (seq
                               (seq
                                (ap result_fold_var $result_test)
                                (canon %init_peer_id% $result_test  #result_iter_canon)
                               )
                               (xor
                                (match #result_iter_canon.length result_incr
                                 (null)
                                )
                                (next result_fold_var)
                               )
                              )
                              (never)
                             )
                            )
                            (canon %init_peer_id% $result_test  #result_result_canon)
                           )
                           (ap #result_result_canon result_gate)
                          )
                         )
                        )
                       )
                      )
                      (xor
                       (call %init_peer_id% ("callbackSrv" "response") [result_gate.$.[0]!])
                       (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "is_deployed",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "service_name" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "blueprint_id" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "unlabeledProduct",
            "items" : [
                {
                    "tag" : "scalar",
                    "name" : "bool"
                }
            ]
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}



export function install(
    ipfs: string,
    worker_def_cid: string,
    config?: {ttl?: number}
): Promise<void>;

export function install(
    peer: IFluenceClient$$,
    ipfs: string,
    worker_def_cid: string,
    config?: {ttl?: number}
): Promise<void>;

export function install(...args: any) {

    let script = `
                    (xor
                     (seq
                      (seq
                       (seq
                        (seq
                         (call %init_peer_id% ("getDataSrv" "-relay-") [] -relay-)
                         (call %init_peer_id% ("getDataSrv" "ipfs") [] ipfs)
                        )
                        (call %init_peer_id% ("getDataSrv" "worker_def_cid") [] worker_def_cid)
                       )
                       (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id)
                      )
                      (xor
                       (seq
                        (call %init_peer_id% ("aqua-ipfs" "cat_from") [worker_def_cid ipfs] json)
                        (xor
                         (match json.$.success! true
                          (xor
                           (seq
                            (seq
                             (seq
                              (seq
                               (seq
                                (seq
                                 (seq
                                  (seq
                                   (seq
                                    (call %init_peer_id% ("json" "parse") [json.$.contents!] worker_definition)
                                    (new $array-inline
                                     (seq
                                      (seq
                                       (ap "parsed worker definition" $array-inline)
                                       (ap worker_definition $array-inline)
                                      )
                                      (canon %init_peer_id% $array-inline  #array-inline-0)
                                     )
                                    )
                                   )
                                   (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-0)
                                  )
                                  (call %init_peer_id% ("debug" "stringify") [#array-inline-0] str)
                                 )
                                 (par
                                  (call %init_peer_id% (spell_id-0 "list_push_string") ["logs" str])
                                  (seq
                                   (new $array-inline-1
                                    (seq
                                     (seq
                                      (ap spell_id-0 $array-inline-1)
                                      (ap #array-inline-0 $array-inline-1)
                                     )
                                     (canon %init_peer_id% $array-inline-1  #array-inline-1-0)
                                    )
                                   )
                                   (call %init_peer_id% ("run-console" "print") [#array-inline-1-0])
                                  )
                                 )
                                )
                                (fold worker_definition.$.services! s-0
                                 (seq
                                  (new $hashes
                                   (xor
                                    (seq
                                     (seq
                                      (seq
                                       (seq
                                        (fold s-0.$.modules! m-0
                                         (seq
                                          (seq
                                           (seq
                                            (seq
                                             (seq
                                              (call %init_peer_id% ("aqua-ipfs" "get_from") [m-0.$.wasm! ipfs] get_wasm)
                                              (call %init_peer_id% ("aqua-ipfs" "cat_from") [m-0.$.config! ipfs] json_cfg)
                                             )
                                             (call %init_peer_id% ("json" "parse") [json_cfg.$.contents!] cfg)
                                            )
                                            (call %init_peer_id% ("dist" "add_module_from_vault") [get_wasm.$.path! cfg] hash)
                                           )
                                           (call %init_peer_id% ("op" "concat_strings") ["hash:" hash] $hashes)
                                          )
                                          (next m-0)
                                         )
                                        )
                                        (par
                                         (canon %init_peer_id% $hashes  #hashes_canon)
                                         (null)
                                        )
                                       )
                                       (call %init_peer_id% ("dist" "make_blueprint") [s-0.$.name! #hashes_canon] blueprint)
                                      )
                                      (call %init_peer_id% ("dist" "add_blueprint") [blueprint] blueprint_id)
                                     )
                                     (xor
                                      (seq
                                       (new $result
                                        (seq
                                         (seq
                                          (seq
                                           (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-1)
                                           (call %init_peer_id% (spell_id-1 "exists") [s-0.$.name!] deployed)
                                          )
                                          (xor
                                           (match deployed.$.flag! true
                                            (xor
                                             (seq
                                              (seq
                                               (call %init_peer_id% ("op" "concat_strings") ["blueprint:" s-0.$.name!] concat_strings)
                                               (call %init_peer_id% (spell_id-1 "get_string") [concat_strings] stored_blueprint)
                                              )
                                              (xor
                                               (match stored_blueprint.$.str! blueprint_id
                                                (ap true $result)
                                               )
                                               (ap false $result)
                                              )
                                             )
                                             (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 1])
                                            )
                                           )
                                           (ap false $result)
                                          )
                                         )
                                         (new $result_test
                                          (seq
                                           (seq
                                            (seq
                                             (call %init_peer_id% ("math" "add") [0 1] result_incr)
                                             (fold $result result_fold_var
                                              (seq
                                               (seq
                                                (ap result_fold_var $result_test)
                                                (canon %init_peer_id% $result_test  #result_iter_canon)
                                               )
                                               (xor
                                                (match #result_iter_canon.length result_incr
                                                 (null)
                                                )
                                                (next result_fold_var)
                                               )
                                              )
                                              (never)
                                             )
                                            )
                                            (canon %init_peer_id% $result_test  #result_result_canon)
                                           )
                                           (ap #result_result_canon result_gate)
                                          )
                                         )
                                        )
                                       )
                                       (match result_gate.$.[0]! false
                                        (xor
                                         (seq
                                          (seq
                                           (seq
                                            (seq
                                             (seq
                                              (seq
                                               (seq
                                                (seq
                                                 (seq
                                                  (call %init_peer_id% (spell_id "set_string") ["status" "install in progress"])
                                                  (call %init_peer_id% ("srv" "create") [blueprint_id] service_id)
                                                 )
                                                 (new $array-inline-2
                                                  (seq
                                                   (seq
                                                    (seq
                                                     (ap "Created service" $array-inline-2)
                                                     (ap s-0.$.name! $array-inline-2)
                                                    )
                                                    (ap service_id $array-inline-2)
                                                   )
                                                   (canon %init_peer_id% $array-inline-2  #array-inline-2-0)
                                                  )
                                                 )
                                                )
                                                (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-2)
                                               )
                                               (call %init_peer_id% ("debug" "stringify") [#array-inline-2-0] str-0)
                                              )
                                              (par
                                               (call %init_peer_id% (spell_id-2 "list_push_string") ["logs" str-0])
                                               (seq
                                                (new $array-inline-3
                                                 (seq
                                                  (seq
                                                   (ap spell_id-2 $array-inline-3)
                                                   (ap #array-inline-2-0 $array-inline-3)
                                                  )
                                                  (canon %init_peer_id% $array-inline-3  #array-inline-3-0)
                                                 )
                                                )
                                                (call %init_peer_id% ("run-console" "print") [#array-inline-3-0])
                                               )
                                              )
                                             )
                                             (xor
                                              (call %init_peer_id% ("srv" "add_alias") [s-0.$.name! service_id])
                                              (seq
                                               (seq
                                                (seq
                                                 (new $array-inline-4
                                                  (seq
                                                   (seq
                                                    (seq
                                                     (seq
                                                      (ap "Error creating alias for deployed service" $array-inline-4)
                                                      (ap s-0.$.name! $array-inline-4)
                                                     )
                                                     (ap service_id $array-inline-4)
                                                    )
                                                    (ap %last_error% $array-inline-4)
                                                   )
                                                   (canon %init_peer_id% $array-inline-4  #array-inline-4-0)
                                                  )
                                                 )
                                                 (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-3)
                                                )
                                                (call %init_peer_id% ("debug" "stringify") [#array-inline-4-0] str-1)
                                               )
                                               (par
                                                (call %init_peer_id% (spell_id-3 "list_push_string") ["logs" str-1])
                                                (seq
                                                 (new $array-inline-5
                                                  (seq
                                                   (seq
                                                    (ap spell_id-3 $array-inline-5)
                                                    (ap #array-inline-4-0 $array-inline-5)
                                                   )
                                                   (canon %init_peer_id% $array-inline-5  #array-inline-5-0)
                                                  )
                                                 )
                                                 (call %init_peer_id% ("run-console" "print") [#array-inline-5-0])
                                                )
                                               )
                                              )
                                             )
                                            )
                                            (call %init_peer_id% (spell_id "set_string") [s-0.$.name! service_id])
                                           )
                                           (call %init_peer_id% ("op" "concat_strings") ["blueprint:" s-0.$.name!] concat_strings-0)
                                          )
                                          (call %init_peer_id% (spell_id "set_string") [concat_strings-0 blueprint_id])
                                         )
                                         (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 2])
                                        )
                                       )
                                      )
                                      (seq
                                       (seq
                                        (seq
                                         (new $array-inline-6
                                          (seq
                                           (seq
                                            (ap s-0.$.name! $array-inline-6)
                                            (ap "is already deployed, doing nothing" $array-inline-6)
                                           )
                                           (canon %init_peer_id% $array-inline-6  #array-inline-6-0)
                                          )
                                         )
                                         (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-4)
                                        )
                                        (call %init_peer_id% ("debug" "stringify") [#array-inline-6-0] str-2)
                                       )
                                       (par
                                        (call %init_peer_id% (spell_id-4 "list_push_string") ["logs" str-2])
                                        (seq
                                         (new $array-inline-7
                                          (seq
                                           (seq
                                            (ap spell_id-4 $array-inline-7)
                                            (ap #array-inline-6-0 $array-inline-7)
                                           )
                                           (canon %init_peer_id% $array-inline-7  #array-inline-7-0)
                                          )
                                         )
                                         (call %init_peer_id% ("run-console" "print") [#array-inline-7-0])
                                        )
                                       )
                                      )
                                     )
                                    )
                                    (seq
                                     (seq
                                      (seq
                                       (new $array-inline-8
                                        (seq
                                         (seq
                                          (seq
                                           (ap "Error deploying service" $array-inline-8)
                                           (ap s-0.$.name! $array-inline-8)
                                          )
                                          (ap %last_error% $array-inline-8)
                                         )
                                         (canon %init_peer_id% $array-inline-8  #array-inline-8-0)
                                        )
                                       )
                                       (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-5)
                                      )
                                      (call %init_peer_id% ("debug" "stringify") [#array-inline-8-0] str-3)
                                     )
                                     (par
                                      (call %init_peer_id% (spell_id-5 "list_push_string") ["logs" str-3])
                                      (seq
                                       (new $array-inline-9
                                        (seq
                                         (seq
                                          (ap spell_id-5 $array-inline-9)
                                          (ap #array-inline-8-0 $array-inline-9)
                                         )
                                         (canon %init_peer_id% $array-inline-9  #array-inline-9-0)
                                        )
                                       )
                                       (call %init_peer_id% ("run-console" "print") [#array-inline-9-0])
                                      )
                                     )
                                    )
                                   )
                                  )
                                  (next s-0)
                                 )
                                )
                               )
                               (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-6)
                              )
                              (call %init_peer_id% ("debug" "stringify") ["Installation finished"] str-4)
                             )
                             (par
                              (call %init_peer_id% (spell_id-6 "list_push_string") ["logs" str-4])
                              (seq
                               (new $array-inline-10
                                (seq
                                 (seq
                                  (ap spell_id-6 $array-inline-10)
                                  (ap "Installation finished" $array-inline-10)
                                 )
                                 (canon %init_peer_id% $array-inline-10  #array-inline-10-0)
                                )
                               )
                               (call %init_peer_id% ("run-console" "print") [#array-inline-10-0])
                              )
                             )
                            )
                            (call %init_peer_id% (spell_id "set_string") ["status" "install finished"])
                           )
                           (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 3])
                          )
                         )
                         (seq
                          (seq
                           (seq
                            (seq
                             (new $array-inline-11
                              (seq
                               (seq
                                (seq
                                 (seq
                                  (ap "Error downloading worker definition from IPFS" $array-inline-11)
                                  (ap ipfs $array-inline-11)
                                 )
                                 (ap worker_def_cid $array-inline-11)
                                )
                                (ap json $array-inline-11)
                               )
                               (canon %init_peer_id% $array-inline-11  #array-inline-11-0)
                              )
                             )
                             (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-7)
                            )
                            (call %init_peer_id% ("debug" "stringify") [#array-inline-11-0] str-5)
                           )
                           (par
                            (call %init_peer_id% (spell_id-7 "list_push_string") ["logs" str-5])
                            (seq
                             (new $array-inline-12
                              (seq
                               (seq
                                (ap spell_id-7 $array-inline-12)
                                (ap #array-inline-11-0 $array-inline-12)
                               )
                               (canon %init_peer_id% $array-inline-12  #array-inline-12-0)
                              )
                             )
                             (call %init_peer_id% ("run-console" "print") [#array-inline-12-0])
                            )
                           )
                          )
                          (call %init_peer_id% (spell_id "set_string") ["status" "install error"])
                         )
                        )
                       )
                       (seq
                        (seq
                         (seq
                          (seq
                           (new $array-inline-13
                            (seq
                             (seq
                              (ap "Error installing worker" $array-inline-13)
                              (ap %last_error% $array-inline-13)
                             )
                             (canon %init_peer_id% $array-inline-13  #array-inline-13-0)
                            )
                           )
                           (call %init_peer_id% ("getDataSrv" "spell_id") [] spell_id-8)
                          )
                          (call %init_peer_id% ("debug" "stringify") [#array-inline-13-0] str-6)
                         )
                         (par
                          (call %init_peer_id% (spell_id-8 "list_push_string") ["logs" str-6])
                          (seq
                           (new $array-inline-14
                            (seq
                             (seq
                              (ap spell_id-8 $array-inline-14)
                              (ap #array-inline-13-0 $array-inline-14)
                             )
                             (canon %init_peer_id% $array-inline-14  #array-inline-14-0)
                            )
                           )
                           (call %init_peer_id% ("run-console" "print") [#array-inline-14-0])
                          )
                         )
                        )
                        (call %init_peer_id% (spell_id "set_string") ["status" "install error"])
                       )
                      )
                     )
                     (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error% 4])
                    )
    `
    return callFunction$$(
        args,
        {
    "functionName" : "install",
    "arrow" : {
        "tag" : "arrow",
        "domain" : {
            "tag" : "labeledProduct",
            "fields" : {
                "ipfs" : {
                    "tag" : "scalar",
                    "name" : "string"
                },
                "worker_def_cid" : {
                    "tag" : "scalar",
                    "name" : "string"
                }
            }
        },
        "codomain" : {
            "tag" : "nil"
        }
    },
    "names" : {
        "relay" : "-relay-",
        "getDataSrv" : "getDataSrv",
        "callbackSrv" : "callbackSrv",
        "responseSrv" : "callbackSrv",
        "responseFnName" : "response",
        "errorHandlingSrv" : "errorHandlingSrv",
        "errorFnName" : "error"
    }
},
        script
    )
}

/* eslint-enable */
