/* eslint-disable */
// @ts-nocheck
/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.10.2
 *
 */
import type { IFluenceClient as IFluenceClient$$, CallParams as CallParams$$ } from '@fluencelabs/js-client.api';
import {
    v5_callFunction as callFunction$$,
    v5_registerService as registerService$$,
} from '@fluencelabs/js-client.api';
    


// Services

export interface SpellDataDef {
    spell_id: (callParams: CallParams$$<null>) => string | Promise<string>;
}
export function registerSpellData(service: SpellDataDef): void;
export function registerSpellData(serviceId: string, service: SpellDataDef): void;
export function registerSpellData(peer: IFluenceClient$$, service: SpellDataDef): void;
export function registerSpellData(peer: IFluenceClient$$, serviceId: string, service: SpellDataDef): void;
       

export function registerSpellData(...args: any) {
    registerService$$(
        args,
        {
    "defaultServiceId" : "getDataSrv",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "spell_id" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "nil"
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "scalar",
                            "name" : "string"
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions


/* eslint-enable */