name: "commit-hook"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"

jobs:
      - name: Run on each commit
        env:
          FLUENCE_USER_DIR: "${{ github.workspace }}/tmp/.fluence"
        if: ${{ github.event_name == 'pull_request' && github.repository == github.event.repository.full_name }}
        run: pnpm on-each-commit

