name: On each commit in PR

on:
  pull_request:
    types:
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fluence-cli
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"
          cache: "pnpm"

      - run: pnpm i

      - name: Run on each commit
        run: pnpm on-each-commit

      - uses: stefanzweifel/git-auto-commit-action@v4
