name: Promote fluence-cli

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "Promote version to channel"
        type: string
        required: true

env:
  CI: true
  FORCE_COLOR: true

jobs:
  promote:
    name: "Promote fcli"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout fluence-cli
        uses: actions/checkout@v4
        with:
          repository: fluencelabs/cli

      - name: Import secrets
        uses: hashicorp/vault-action@v3.0.0
        id: secrets
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/ci/fcli-binaries id | AWS_ACCESS_KEY_ID ;
            kv/ci/fcli-binaries secret | AWS_SECRET_ACCESS_KEY

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.3"
          registry-url: "https://npm.fluence.dev"
          cache: "yarn"

      - run: yarn install
        working-directory: cli

      - name: Promote fluence-cli
        working-directory: cli
        run: yarn oclif promote -t linux-x64,darwin-x64,darwin-arm64 --version "$(jq .[] -r ../.github/release-please/manifest.json)" --sha "$(git rev-parse --short HEAD)" --channel ${{ inputs.channel }} --no-xz --indexes

      - name: Promote fluence-cli windows
        working-directory: cli
        run: yarn oclif promote -t win32-x64 --version "$(jq .[] -r ../.github/release-please/manifest.json)" --sha "$(git rev-parse --short HEAD)" --channel ${{ inputs.channel }} --no-xz --win --indexes
