name: "test"

on:
  pull_request:
    paths-ignore:
      - "!**.md"
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  fluence-cli:
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
      nox-image: "docker.fluence.dev/nox:feat-vm-425-aquavm-mem-limits-from-config-2_5050_1"
